version: '3'

services:

  integrated:
    image: conciso/seacon2017-integrated
    container_name: integrated
    ports:
    - "8081:8080"
    links:
    - toxiproxy:ldap

  federated:
    image: conciso/seacon2017-federated
    container_name: federated
    ports:
    - "8082:8080"
    
  keycloak:
    image: jboss/keycloak:3.0.0.Final
    container_name: keycloak
    volumes:
    - ../keycloak:/tmp/realm:ro
    ports:
    - "9080:8080"
    links:
     - toxiproxy:ldap
    command: -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm/realm.json

  toxiproxy:
    image: shopify/toxiproxy:2.1.0
    container_name: toxiproxy
    links:
    - openldap:openldap
    ports:
    - "8474:8474"
    volumes:
    - ./:/config:ro
    command: -config /config/proxies.json -host toxiproxy

  openldap:
    image: osixia/openldap:1.1.8
    container_name: openldap
    volumes:
    - ../openldap/database:/var/lib/ldap
    - ../openldap/config:/etc/ldap/slapd.d











  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "10080:80"
    links:
      - openldap:openldap